### ISSUE TITLE
Module Support

### ISSUE THREAD

**Issue by hscells** [mauricioadams/frankjs#1]
Is there any possibility of adding support for requiring this as a module?

**Comment by mauricioadams** [comment]
Hi,
Can you give me some more info on how you would like to use this integrated with?

Thanks.

**Comment by hscells** [comment]
how about an API to it like

```
frankjs("http://www.google.com",function(error,result){
 console.log(result);
})
```

**Comment by mauricioadams** [comment]
Thats a good feature, I'll put that in my TODO list.

Thanks for the suggestion!
